/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Slid To-Do API
 * 할 일·목표 관리 서비스 슬리드투두의 REST API입니다. 모든 경로에 teamId가 포함되며, Auth 엔드포인트를 제외한 모든 요청에 Authorization: Bearer {accessToken} 헤더가 필요합니다.

## teamId
teamId는 팀별로 고유한 문자열입니다. 프론트엔드 과제에서는 주어진 teamId를 경로에 그대로 사용하세요.

## 페이지네이션
대부분의 목록 API는 숫자 ID 기반 커서를 사용합니다. Posts·Comments만 인코딩된 문자열 커서를 사용하며, 두 경우 모두 nextCursor 값을 그대로 다음 요청의 cursor 파라미터에 전달하면 됩니다.

## 공통 에러 포맷
모든 에러 응답은 `{ "message": "에러 상세", "code": "ERROR_CODE" }` 형태입니다.
 * OpenAPI spec version: 1.0.0
 */
import type {
  PostTeamIdAuthLogin200,
  PostTeamIdAuthLoginBody,
  PostTeamIdAuthLogout200,
  PostTeamIdAuthLogoutBody,
  PostTeamIdAuthRefresh200,
  PostTeamIdAuthRefreshBody,
  PostTeamIdAuthSignup201,
  PostTeamIdAuthSignupBody,
  PostTeamIdOauthProvider200,
  PostTeamIdOauthProviderBody,
} from ".././model";

import { customInstance } from "../axiosInstance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 이메일, 비밀번호로 계정 생성됩니다. 이메일은 이메일 주소 형식이며, 비밀번호는 8자 이상 입력해야 합니다. 공통 accessToken, refreshToken, user 정보를 반환합니다.
 * @summary 회원가입
 */
export const postTeamIdAuthSignup = (
  teamId: string,
  postTeamIdAuthSignupBody: PostTeamIdAuthSignupBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PostTeamIdAuthSignup201>(
    {
      url: `/${teamId}/auth/signup`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postTeamIdAuthSignupBody,
      signal,
    },
    options,
  );
};

/**
 * 이메일과 비밀번호로 로그인합니다. OAuth가 한 계정은 이메일과 비밀번호 로그인이 불가능합니다.
 * @summary 로그인
 */
export const postTeamIdAuthLogin = (
  teamId: string,
  postTeamIdAuthLoginBody: PostTeamIdAuthLoginBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PostTeamIdAuthLogin200>(
    {
      url: `/${teamId}/auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postTeamIdAuthLoginBody,
      signal,
    },
    options,
  );
};

/**
 * refreshToken으로 토큰을 발급받습니다. 기존 refreshToken은 즉시 기간만료합니다.(토큰 로테이션). 해당 용의 refreshToken을 사용하여 보안해결하여 해당 용의 모든 세션 만료합니다.
 * @summary 토큰 재발급
 */
export const postTeamIdAuthRefresh = (
  teamId: string,
  postTeamIdAuthRefreshBody: PostTeamIdAuthRefreshBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PostTeamIdAuthRefresh200>(
    {
      url: `/${teamId}/auth/refresh`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postTeamIdAuthRefreshBody,
      signal,
    },
    options,
  );
};

/**
 * refreshToken으로 로그아웃합니다. accessToken은 만료 기간까지 효력이 있습니다.
 * @summary 로그아웃
 */
export const postTeamIdAuthLogout = (
  teamId: string,
  postTeamIdAuthLogoutBody: PostTeamIdAuthLogoutBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PostTeamIdAuthLogout200>(
    {
      url: `/${teamId}/auth/logout`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postTeamIdAuthLogoutBody,
      signal,
    },
    options,
  );
};

/**
 * Google는 Kakao OAuth 세큰으로 로그인합니다. 최초 로그인 동시로 계정 생성되며, 이후는 로그인 보가 데이트되며, 같은 이메일로 이메일 가입 계정으로 409 에러가 발생합니다.
 * @summary OAuth 로그인
 */
export const postTeamIdOauthProvider = (
  teamId: string,
  provider: "google" | "kakao",
  postTeamIdOauthProviderBody: PostTeamIdOauthProviderBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PostTeamIdOauthProvider200>(
    {
      url: `/${teamId}/oauth/${provider}`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postTeamIdOauthProviderBody,
      signal,
    },
    options,
  );
};
