/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Slid To-Do API
 * 할 일·목표 관리 서비스 슬리드투두의 REST API입니다. 모든 경로에 teamId가 포함되며, Auth 엔드포인트를 제외한 모든 요청에 Authorization: Bearer {accessToken} 헤더가 필요합니다.

## teamId
teamId는 팀별로 고유한 문자열입니다. 프론트엔드 과제에서는 주어진 teamId를 경로에 그대로 사용하세요.

## 페이지네이션
대부분의 목록 API는 숫자 ID 기반 커서를 사용합니다. Posts·Comments만 인코딩된 문자열 커서를 사용하며, 두 경우 모두 nextCursor 값을 그대로 다음 요청의 cursor 파라미터에 전달하면 됩니다.

## 공통 에러 포맷
모든 에러 응답은 `{ "message": "에러 상세", "code": "ERROR_CODE" }` 형태입니다.
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetTeamIdUsersCheckNickname200,
  GetTeamIdUsersCheckNicknameParams,
  GetTeamIdUsersMe200,
  PatchTeamIdUsersMe200,
  PatchTeamIdUsersMeBody,
  PatchTeamIdUsersMePassword200,
  PatchTeamIdUsersMePasswordBody,
} from ".././model";

import { customInstance } from "../axiosInstance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 해당 팀 내에서 닉네임(name)이 이미 사용 중인지 확인합니다.
 * @summary 닉네임 중복 확인
 */
export const getTeamIdUsersCheckNickname = (
  teamId: string,
  params: GetTeamIdUsersCheckNicknameParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetTeamIdUsersCheckNickname200>(
    { url: `/${teamId}/users/check-nickname`, method: "GET", params, signal },
    options,
  );
};

/**
 * 현재 로그인한 사용자의 프로필 정보를 조회합니다.
 * @summary 내 프로필 조회
 */
export const getTeamIdUsersMe = (
  teamId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetTeamIdUsersMe200>(
    { url: `/${teamId}/users/me`, method: "GET", signal },
    options,
  );
};

/**
 * 현재 로그인한 사용자의 프로필을 수정합니다. name과 image 중 최소 하나의 필드를 포함해야 합니다. image를 null로 설정하면 프로필 이미지가 제거됩니다.
 * @summary 내 프로필 수정
 */
export const patchTeamIdUsersMe = (
  teamId: string,
  patchTeamIdUsersMeBody: PatchTeamIdUsersMeBody,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<PatchTeamIdUsersMe200>(
    {
      url: `/${teamId}/users/me`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchTeamIdUsersMeBody,
    },
    options,
  );
};

/**
 * 현재 로그인한 사용자의 계정을 삭제합니다. 관련된 모든 데이터(목표, 할 일, 노트, 게시글, 댓글 등)가 함께 삭제됩니다.
 * @summary 계정 삭제
 */
export const deleteTeamIdUsersMe = (
  teamId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/${teamId}/users/me`, method: "DELETE" },
    options,
  );
};

/**
 * 현재 비밀번호를 확인한 후 새 비밀번호로 변경합니다. OAuth로 가입한 계정은 비밀번호 변경이 불가합니다.
 * @summary 비밀번호 변경
 */
export const patchTeamIdUsersMePassword = (
  teamId: string,
  patchTeamIdUsersMePasswordBody: PatchTeamIdUsersMePasswordBody,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<PatchTeamIdUsersMePassword200>(
    {
      url: `/${teamId}/users/me/password`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchTeamIdUsersMePasswordBody,
    },
    options,
  );
};
