/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Slid To-Do API
 * 할 일·목표 관리 서비스 슬리드투두의 REST API입니다. 모든 경로에 teamId가 포함되며, Auth 엔드포인트를 제외한 모든 요청에 Authorization: Bearer {accessToken} 헤더가 필요합니다.

## teamId
teamId는 팀별로 고유한 문자열입니다. 프론트엔드 과제에서는 주어진 teamId를 경로에 그대로 사용하세요.

## 페이지네이션
대부분의 목록 API는 숫자 ID 기반 커서를 사용합니다. Posts·Comments만 인코딩된 문자열 커서를 사용하며, 두 경우 모두 nextCursor 값을 그대로 다음 요청의 cursor 파라미터에 전달하면 됩니다.

## 공통 에러 포맷
모든 에러 응답은 `{ "message": "에러 상세", "code": "ERROR_CODE" }` 형태입니다.
 * OpenAPI spec version: 1.0.0
 */
import type {
  DeleteTeamIdPostsPostIdCommentsCommentIdLikes200,
  GetTeamIdPostsPostIdComments200,
  GetTeamIdPostsPostIdCommentsParams,
  PatchTeamIdPostsPostIdCommentsCommentId200,
  PatchTeamIdPostsPostIdCommentsCommentIdBody,
  PostTeamIdPostsPostIdComments201,
  PostTeamIdPostsPostIdCommentsBody,
  PostTeamIdPostsPostIdCommentsCommentIdLikes200,
} from ".././model";

import { customInstance } from "../axiosInstance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 커서 기반 페이지네이션으로 게시글의 댓글 목록을 조회합니다. nextCursor가 null이면 마지막 페이지입니다. parentId를 생략하면 일반 댓글과 대댓글이 함께 반환됩니다. parentId=null이면 최상위 댓글만, parentId=부모댓글ID이면 해당 댓글의 대댓글만 조회합니다(무한 스크롤 분리용).
 * @summary 댓글 목록 조회
 */
export const getTeamIdPostsPostIdComments = (
  teamId: string,
  postId: number,
  params?: GetTeamIdPostsPostIdCommentsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetTeamIdPostsPostIdComments200>(
    {
      url: `/${teamId}/posts/${postId}/comments`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

/**
 * 게시글에 댓글 또는 대댓글을 작성합니다. parentId를 주면 해당 댓글의 대댓글로 생성됩니다.
 * @summary 댓글 생성
 */
export const postTeamIdPostsPostIdComments = (
  teamId: string,
  postId: number,
  postTeamIdPostsPostIdCommentsBody: PostTeamIdPostsPostIdCommentsBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PostTeamIdPostsPostIdComments201>(
    {
      url: `/${teamId}/posts/${postId}/comments`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postTeamIdPostsPostIdCommentsBody,
      signal,
    },
    options,
  );
};

/**
 * 댓글 내용을 수정합니다. 본인 작성 댓글만 수정할 수 있습니다.
 * @summary 댓글 수정
 */
export const patchTeamIdPostsPostIdCommentsCommentId = (
  teamId: string,
  postId: number,
  commentId: number,
  patchTeamIdPostsPostIdCommentsCommentIdBody: PatchTeamIdPostsPostIdCommentsCommentIdBody,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<PatchTeamIdPostsPostIdCommentsCommentId200>(
    {
      url: `/${teamId}/posts/${postId}/comments/${commentId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchTeamIdPostsPostIdCommentsCommentIdBody,
    },
    options,
  );
};

/**
 * 댓글을 삭제합니다. 본인 작성 댓글만 삭제할 수 있습니다.
 * @summary 댓글 삭제
 */
export const deleteTeamIdPostsPostIdCommentsCommentId = (
  teamId: string,
  postId: number,
  commentId: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    {
      url: `/${teamId}/posts/${postId}/comments/${commentId}`,
      method: "DELETE",
    },
    options,
  );
};

/**
 * 댓글에 좋아요를 추가합니다. 이미 좋아요한 경우 멱등적으로 현재 상태를 반환합니다.
 * @summary 댓글 좋아요
 */
export const postTeamIdPostsPostIdCommentsCommentIdLikes = (
  teamId: string,
  postId: number,
  commentId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PostTeamIdPostsPostIdCommentsCommentIdLikes200>(
    {
      url: `/${teamId}/posts/${postId}/comments/${commentId}/likes`,
      method: "POST",
      signal,
    },
    options,
  );
};

/**
 * 댓글 좋아요를 취소합니다. 좋아요가 없어도 성공으로 처리하며, 현재 좋아요 수와 사용자 좋아요 여부를 반환합니다.
 * @summary 댓글 좋아요 취소
 */
export const deleteTeamIdPostsPostIdCommentsCommentIdLikes = (
  teamId: string,
  postId: number,
  commentId: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<DeleteTeamIdPostsPostIdCommentsCommentIdLikes200>(
    {
      url: `/${teamId}/posts/${postId}/comments/${commentId}/likes`,
      method: "DELETE",
    },
    options,
  );
};
