/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Slid To-Do API
 * 할 일·목표 관리 서비스 슬리드투두의 REST API입니다. 모든 경로에 teamId가 포함되며, Auth 엔드포인트를 제외한 모든 요청에 Authorization: Bearer {accessToken} 헤더가 필요합니다.

## teamId
teamId는 팀별로 고유한 문자열입니다. 프론트엔드 과제에서는 주어진 teamId를 경로에 그대로 사용하세요.

## 페이지네이션
대부분의 목록 API는 숫자 ID 기반 커서를 사용합니다. Posts·Comments만 인코딩된 문자열 커서를 사용하며, 두 경우 모두 nextCursor 값을 그대로 다음 요청의 cursor 파라미터에 전달하면 됩니다.

## 공통 에러 포맷
모든 에러 응답은 `{ "message": "에러 상세", "code": "ERROR_CODE" }` 형태입니다.
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetTeamIdTodosFavorites200,
  GetTeamIdTodosFavoritesParams,
  PostTeamIdTodosTodoIdFavorites201,
} from ".././model";

import { customInstance } from "../axiosInstance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 할 일을 찜합니다. 본인 소유의 할 일만 찜할 수 있습니다. 이미 찜한 할 일을 다시 찜하면 409 에러가 반환됩니다.
 * @summary 할 일 찜하기
 */
export const postTeamIdTodosTodoIdFavorites = (
  teamId: string,
  todoId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PostTeamIdTodosTodoIdFavorites201>(
    { url: `/${teamId}/todos/${todoId}/favorites`, method: "POST", signal },
    options,
  );
};

/**
 * 할 일의 찜을 해제합니다.
 * @summary 찜 해제
 */
export const deleteTeamIdTodosTodoIdFavorites = (
  teamId: string,
  todoId: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/${teamId}/todos/${todoId}/favorites`, method: "DELETE" },
    options,
  );
};

/**
 * 커서 기반 페이지네이션으로 찜한 할 일 목록을 조회합니다. 각 항목에 연결된 할 일(todo)과 목표(goal) 정보가 포함됩니다. nextCursor가 null이면 마지막 페이지입니다.
 * @summary 찜한 할 일 목록 조회
 */
export const getTeamIdTodosFavorites = (
  teamId: string,
  params?: GetTeamIdTodosFavoritesParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetTeamIdTodosFavorites200>(
    { url: `/${teamId}/todos/favorites`, method: "GET", params, signal },
    options,
  );
};
