/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Slid To-Do API
 * 할 일·목표 관리 서비스 슬리드투두의 REST API입니다. 모든 경로에 teamId가 포함되며, Auth 엔드포인트를 제외한 모든 요청에 Authorization: Bearer {accessToken} 헤더가 필요합니다.

## teamId
teamId는 팀별로 고유한 문자열입니다. 프론트엔드 과제에서는 주어진 teamId를 경로에 그대로 사용하세요.

## 페이지네이션
대부분의 목록 API는 숫자 ID 기반 커서를 사용합니다. Posts·Comments만 인코딩된 문자열 커서를 사용하며, 두 경우 모두 nextCursor 값을 그대로 다음 요청의 cursor 파라미터에 전달하면 됩니다.

## 공통 에러 포맷
모든 에러 응답은 `{ "message": "에러 상세", "code": "ERROR_CODE" }` 형태입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { GetTeamIdNotesSort } from "./getTeamIdNotesSort";

export type GetTeamIdNotesParams = {
  /**
   * 이전 응답의 nextCursor 값
   * @minimum 0
   * @exclusiveMinimum
   */
  cursor?: number;
  /**
   * 한 페이지에 가져올 항목 수 (1-100, 기본값 10)
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * 특정 할 일의 노트만 필터링
   * @minimum 0
   * @exclusiveMinimum
   */
  todoId?: number;
  /**
   * 특정 목표의 노트만 필터링 (목표에 속한 할 일의 노트)
   * @minimum 0
   * @exclusiveMinimum
   */
  goalId?: number;
  /**
   * 노트 제목 부분 일치 검색 (대소문자 무시, 생략 시 필터 없음)
   * @maxLength 200
   */
  search?: string;
  /**
   * 정렬 기준 ("latest" | "oldest", 기본값 "latest")
   */
  sort?: GetTeamIdNotesSort;
};
