/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Slid To-Do API
 * 할 일·목표 관리 서비스 슬리드투두의 REST API입니다. 모든 경로에 teamId가 포함되며, Auth 엔드포인트를 제외한 모든 요청에 Authorization: Bearer {accessToken} 헤더가 필요합니다.

## teamId
teamId는 팀별로 고유한 문자열입니다. 프론트엔드 과제에서는 주어진 teamId를 경로에 그대로 사용하세요.

## 페이지네이션
대부분의 목록 API는 숫자 ID 기반 커서를 사용합니다. Posts·Comments만 인코딩된 문자열 커서를 사용하며, 두 경우 모두 nextCursor 값을 그대로 다음 요청의 cursor 파라미터에 전달하면 됩니다.

## 공통 에러 포맷
모든 에러 응답은 `{ "message": "에러 상세", "code": "ERROR_CODE" }` 형태입니다.
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetTeamIdNotifications200,
  GetTeamIdNotificationsParams,
  PatchTeamIdNotificationsNotificationId200,
  PatchTeamIdNotificationsNotificationIdBody,
} from ".././model";

import { customInstance } from "../axiosInstance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 커서 기반 페이지네이션으로 본인의 알림 목록을 조회합니다. 최신 알림이 먼저 표시됩니다. 알림은 댓글, 할 일 완료, 목표 달성 시 자동으로 생성됩니다. nextCursor가 null이면 마지막 페이지입니다.
 * @summary 알림 목록 조회
 */
export const getTeamIdNotifications = (
  params?: GetTeamIdNotificationsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetTeamIdNotifications200>(
    { url: `/notifications`, method: "GET", params, signal },
    options,
  );
};

/**
 * 본인의 모든 알림을 읽음 처리합니다.
 * @summary 전체 알림 읽음 처리
 */
export const patchTeamIdNotifications = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/notifications`, method: "PATCH" },
    options,
  );
};

/**
 * 본인의 알림을 전부 삭제합니다. 되돌릴 수 없습니다.
 * @summary 전체 알림 삭제
 */
export const deleteTeamIdNotifications = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/notifications`, method: "DELETE" },
    options,
  );
};

/**
 * 알림의 읽음 상태를 변경합니다. 본인의 알림만 수정 가능합니다.
 * @summary 알림 읽음 상태 변경
 */
export const patchTeamIdNotificationsNotificationId = (
  notificationId: number,
  patchTeamIdNotificationsNotificationIdBody: PatchTeamIdNotificationsNotificationIdBody,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<PatchTeamIdNotificationsNotificationId200>(
    {
      url: `/notifications/${notificationId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchTeamIdNotificationsNotificationIdBody,
    },
    options,
  );
};

/**
 * 알림 1건을 삭제합니다. 본인의 알림만 삭제 가능합니다.
 * @summary 알림 단건 삭제
 */
export const deleteTeamIdNotificationsNotificationId = (
  notificationId: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/notifications/${notificationId}`, method: "DELETE" },
    options,
  );
};
