/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Slid To-Do API
 * 할 일·목표 관리 서비스 슬리드투두의 REST API입니다. 모든 경로에 teamId가 포함되며, Auth 엔드포인트를 제외한 모든 요청에 Authorization: Bearer {accessToken} 헤더가 필요합니다.

## teamId
teamId는 팀별로 고유한 문자열입니다. 프론트엔드 과제에서는 주어진 teamId를 경로에 그대로 사용하세요.

## 페이지네이션
대부분의 목록 API는 숫자 ID 기반 커서를 사용합니다. Posts·Comments만 인코딩된 문자열 커서를 사용하며, 두 경우 모두 nextCursor 값을 그대로 다음 요청의 cursor 파라미터에 전달하면 됩니다.

## 공통 에러 포맷
모든 에러 응답은 `{ "message": "에러 상세", "code": "ERROR_CODE" }` 형태입니다.
 * OpenAPI spec version: 1.0.0
 */
import type {
  DeleteTeamIdGoalsGoalId401,
  DeleteTeamIdGoalsGoalId403,
  DeleteTeamIdGoalsGoalId404,
  GetTeamIdGoals200,
  GetTeamIdGoals400,
  GetTeamIdGoals401,
  GetTeamIdGoalsGoalId200,
  GetTeamIdGoalsGoalId401,
  GetTeamIdGoalsGoalId403,
  GetTeamIdGoalsGoalId404,
  GetTeamIdGoalsParams,
  PatchTeamIdGoalsGoalId200,
  PatchTeamIdGoalsGoalId400,
  PatchTeamIdGoalsGoalId401,
  PatchTeamIdGoalsGoalId403,
  PatchTeamIdGoalsGoalId404,
  PatchTeamIdGoalsGoalIdBody,
  PostTeamIdGoals201,
  PostTeamIdGoals400,
  PostTeamIdGoals401,
  PostTeamIdGoalsBody,
} from ".././model";

import { customInstance } from "../axiosInstance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 커서 기반 페이지네이션으로 본인의 목표 목록을 조회합니다. 각 목표에 todoCount(전체 할 일 수)와 completedCount(완료 수)가 포함됩니다. nextCursor가 null이면 마지막 페이지입니다.
 * @summary 목표 목록 조회
 */
export const getTeamIdGoals = (
  teamId: string,
  params?: GetTeamIdGoalsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetTeamIdGoals200>(
    { url: `/${teamId}/goals`, method: "GET", params, signal },
    options,
  );
};

/**
 * 새 목표를 생성합니다. title은 1~100자입니다.
 * @summary 목표 생성
 */
export const postTeamIdGoals = (
  teamId: string,
  postTeamIdGoalsBody: PostTeamIdGoalsBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PostTeamIdGoals201>(
    {
      url: `/${teamId}/goals`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postTeamIdGoalsBody,
      signal,
    },
    options,
  );
};

/**
 * 목표 상세 정보를 조회합니다. 해당 목표에 속한 할 일 목록(todos)이 함께 포함됩니다.
 * @summary 목표 상세 조회
 */
export const getTeamIdGoalsGoalId = (
  teamId: string,
  goalId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetTeamIdGoalsGoalId200>(
    { url: `/${teamId}/goals/${goalId}`, method: "GET", signal },
    options,
  );
};

/**
 * 목표 제목을 수정합니다. 본인 소유 목표만 수정 가능합니다.
 * @summary 목표 수정
 */
export const patchTeamIdGoalsGoalId = (
  teamId: string,
  goalId: number,
  patchTeamIdGoalsGoalIdBody: PatchTeamIdGoalsGoalIdBody,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<PatchTeamIdGoalsGoalId200>(
    {
      url: `/${teamId}/goals/${goalId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchTeamIdGoalsGoalIdBody,
    },
    options,
  );
};

/**
 * 목표를 삭제합니다. 연결된 할 일의 goalId가 null로 변경됩니다 (할 일 자체는 삭제되지 않음).
 * @summary 목표 삭제
 */
export const deleteTeamIdGoalsGoalId = (
  teamId: string,
  goalId: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/${teamId}/goals/${goalId}`, method: "DELETE" },
    options,
  );
};
