/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Slid To-Do API
 * 할 일·목표 관리 서비스 슬리드투두의 REST API입니다. 모든 경로에 teamId가 포함되며, Auth 엔드포인트를 제외한 모든 요청에 Authorization: Bearer {accessToken} 헤더가 필요합니다.

## teamId
teamId는 팀별로 고유한 문자열입니다. 프론트엔드 과제에서는 주어진 teamId를 경로에 그대로 사용하세요.

## 페이지네이션
대부분의 목록 API는 숫자 ID 기반 커서를 사용합니다. Posts·Comments만 인코딩된 문자열 커서를 사용하며, 두 경우 모두 nextCursor 값을 그대로 다음 요청의 cursor 파라미터에 전달하면 됩니다.

## 공통 에러 포맷
모든 에러 응답은 `{ "message": "에러 상세", "code": "ERROR_CODE" }` 형태입니다.
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetTeamIdPosts200,
  GetTeamIdPostsParams,
  GetTeamIdPostsPostId200,
  PatchTeamIdPostsPostId200,
  PatchTeamIdPostsPostIdBody,
  PostTeamIdPosts201,
  PostTeamIdPostsBody,
} from ".././model";

import { customInstance } from "../axiosInstance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 커서 기반 페이지네이션으로 게시글 목록을 조회합니다. 팀 전체 공개 게시판이므로 팀 내 모든 게시글이 조회됩니다. type=all(기본)은 최신순, type=best는 조회수 높은 순으로 정렬합니다. search로 제목·본문 부분 검색이 가능합니다. nextCursor가 null이면 마지막 페이지입니다.
 * @summary 게시글 목록 조회
 */
export const getTeamIdPosts = (
  params?: GetTeamIdPostsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetTeamIdPosts200>(
    { url: `/posts`, method: "GET", params, signal },
    options,
  );
};

/**
 * 새 게시글을 생성합니다. title과 content가 필수이며, image URL을 선택적으로 첨부할 수 있습니다.
 * @summary 게시글 생성
 */
export const postTeamIdPosts = (
  postTeamIdPostsBody: PostTeamIdPostsBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PostTeamIdPosts201>(
    {
      url: `/posts`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postTeamIdPostsBody,
      signal,
    },
    options,
  );
};

/**
 * 게시글의 상세 정보를 조회합니다. 조회 시 조회수(viewCount)가 자동으로 1 증가합니다. 작성자(writer) 정보와 댓글 수(commentCount)가 포함됩니다.
 * @summary 게시글 상세 조회
 */
export const getTeamIdPostsPostId = (
  postId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetTeamIdPostsPostId200>(
    { url: `/posts/${postId}`, method: "GET", signal },
    options,
  );
};

/**
 * 게시글을 부분 수정합니다. 본인 작성 게시글만 수정할 수 있습니다. 최소 1개 필드를 보내야 합니다. image에 null을 보내면 이미지를 제거합니다.
 * @summary 게시글 수정
 */
export const patchTeamIdPostsPostId = (
  postId: number,
  patchTeamIdPostsPostIdBody: PatchTeamIdPostsPostIdBody,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<PatchTeamIdPostsPostId200>(
    {
      url: `/posts/${postId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchTeamIdPostsPostIdBody,
    },
    options,
  );
};

/**
 * 게시글을 삭제합니다. 본인 작성 게시글만 삭제할 수 있습니다. 연결된 댓글도 함께 삭제됩니다 (cascade).
 * @summary 게시글 삭제
 */
export const deleteTeamIdPostsPostId = (
  postId: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/posts/${postId}`, method: "DELETE" },
    options,
  );
};
