/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Slid To-Do API
 * 할 일·목표 관리 서비스 슬리드투두의 REST API입니다. 모든 경로에 teamId가 포함되며, Auth 엔드포인트를 제외한 모든 요청에 Authorization: Bearer {accessToken} 헤더가 필요합니다.

## teamId
teamId는 팀별로 고유한 문자열입니다. 프론트엔드 과제에서는 주어진 teamId를 경로에 그대로 사용하세요.

## 페이지네이션
대부분의 목록 API는 숫자 ID 기반 커서를 사용합니다. Posts·Comments만 인코딩된 문자열 커서를 사용하며, 두 경우 모두 nextCursor 값을 그대로 다음 요청의 cursor 파라미터에 전달하면 됩니다.

## 공통 에러 포맷
모든 에러 응답은 `{ "message": "에러 상세", "code": "ERROR_CODE" }` 형태입니다.
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetTeamIdTodos200,
  GetTeamIdTodosParams,
  GetTeamIdTodosTodoId200,
  PatchTeamIdTodosTodoId200,
  PatchTeamIdTodosTodoIdBody,
  PostTeamIdTodos201,
  PostTeamIdTodosBody,
} from ".././model";

import { customInstance } from "../axiosInstance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 커서 기반 페이지네이션으로 할 일 목록을 조회합니다. goalId로 특정 목표의 할 일만, done으로 완료/미완료를 필터링할 수 있습니다. date로 특정 날짜(KST), from/to로 마감일 범위(KST)를 필터링할 수 있습니다. sort로 최신순(latest) 또는 마감일 임박순(dueSoon) 정렬을 선택할 수 있습니다. nextCursor가 null이면 마지막 페이지입니다.
 * @summary 할 일 목록 조회
 */
export const getTeamIdTodos = (
  teamId: string,
  params?: GetTeamIdTodosParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetTeamIdTodos200>(
    { url: `/${teamId}/todos`, method: "GET", params, signal },
    options,
  );
};

/**
 * 새 할 일을 생성합니다. title만 필수이며, goalId를 지정하면 해당 목표에 연결됩니다 (본인 소유 목표만 가능).
 * @summary 할 일 생성
 */
export const postTeamIdTodos = (
  teamId: string,
  postTeamIdTodosBody: PostTeamIdTodosBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PostTeamIdTodos201>(
    {
      url: `/${teamId}/todos`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postTeamIdTodosBody,
      signal,
    },
    options,
  );
};

/**
 * 할 일의 상세 정보를 조회합니다. 연결된 목표(goal)와 노트 ID 목록(noteIds)이 포함됩니다.
 * @summary 할 일 상세 조회
 */
export const getTeamIdTodosTodoId = (
  teamId: string,
  todoId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetTeamIdTodosTodoId200>(
    { url: `/${teamId}/todos/${todoId}`, method: "GET", signal },
    options,
  );
};

/**
 * 할 일을 부분 수정합니다. 최소 1개 필드를 보내야 합니다. goalId/fileUrl/linkUrl에 null을 보내면 연결을 해제하고, 필드를 아예 보내지 않으면 기존 값이 유지됩니다.
 * @summary 할 일 수정
 */
export const patchTeamIdTodosTodoId = (
  teamId: string,
  todoId: number,
  patchTeamIdTodosTodoIdBody: PatchTeamIdTodosTodoIdBody,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<PatchTeamIdTodosTodoId200>(
    {
      url: `/${teamId}/todos/${todoId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchTeamIdTodosTodoIdBody,
    },
    options,
  );
};

/**
 * 할 일을 삭제합니다. 연결된 노트와 찜하기도 함께 삭제됩니다 (cascade).
 * @summary 할 일 삭제
 */
export const deleteTeamIdTodosTodoId = (
  teamId: string,
  todoId: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/${teamId}/todos/${todoId}`, method: "DELETE" },
    options,
  );
};
