/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Slid To-Do API
 * 할 일·목표 관리 서비스 슬리드투두의 REST API입니다. 모든 경로에 teamId가 포함되며, Auth 엔드포인트를 제외한 모든 요청에 Authorization: Bearer {accessToken} 헤더가 필요합니다.

## teamId
teamId는 팀별로 고유한 문자열입니다. 프론트엔드 과제에서는 주어진 teamId를 경로에 그대로 사용하세요.

## 페이지네이션
대부분의 목록 API는 숫자 ID 기반 커서를 사용합니다. Posts·Comments만 인코딩된 문자열 커서를 사용하며, 두 경우 모두 nextCursor 값을 그대로 다음 요청의 cursor 파라미터에 전달하면 됩니다.

## 공통 에러 포맷
모든 에러 응답은 `{ "message": "에러 상세", "code": "ERROR_CODE" }` 형태입니다.
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetTeamIdNotes200,
  GetTeamIdNotesNoteId200,
  GetTeamIdNotesParams,
  PatchTeamIdNotesNoteId200,
  PatchTeamIdNotesNoteIdBody,
  PostTeamIdNotes201,
  PostTeamIdNotesBody,
} from ".././model";

import { customInstance } from "../axiosInstance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 커서 기반 페이지네이션으로 노트 목록을 조회합니다. todoId/goalId로 필터링할 수 있고, search로 제목 부분 검색이 가능하며, sort로 최신순(latest) 또는 오래된 순(oldest) 정렬을 선택할 수 있습니다. nextCursor가 null이면 마지막 페이지입니다.
 * @summary 노트 목록 조회
 */
export const getTeamIdNotes = (
  teamId: string,
  params?: GetTeamIdNotesParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetTeamIdNotes200>(
    { url: `/${teamId}/notes`, method: "GET", params, signal },
    options,
  );
};

/**
 * 새 노트를 생성합니다. todoId와 title이 필수입니다. 하나의 할 일에 여러 노트를 연결할 수 있습니다 (1:N).
 * @summary 노트 생성
 */
export const postTeamIdNotes = (
  teamId: string,
  postTeamIdNotesBody: PostTeamIdNotesBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PostTeamIdNotes201>(
    {
      url: `/${teamId}/notes`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postTeamIdNotesBody,
      signal,
    },
    options,
  );
};

/**
 * 노트의 상세 정보를 조회합니다. 연결된 할 일(todo)의 생성일/목표(goal)/태그(tags) 정보가 포함됩니다.
 * @summary 노트 상세 조회
 */
export const getTeamIdNotesNoteId = (
  teamId: string,
  noteId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetTeamIdNotesNoteId200>(
    { url: `/${teamId}/notes/${noteId}`, method: "GET", signal },
    options,
  );
};

/**
 * 노트를 부분 수정합니다. 최소 1개 필드를 보내야 합니다. content/linkUrl에 null을 보내면 값을 제거하고, 필드를 아예 보내지 않으면 기존 값이 유지됩니다. todoId는 변경할 수 없습니다.
 * @summary 노트 수정
 */
export const patchTeamIdNotesNoteId = (
  teamId: string,
  noteId: number,
  patchTeamIdNotesNoteIdBody: PatchTeamIdNotesNoteIdBody,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<PatchTeamIdNotesNoteId200>(
    {
      url: `/${teamId}/notes/${noteId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchTeamIdNotesNoteIdBody,
    },
    options,
  );
};

/**
 * 노트를 삭제합니다.
 * @summary 노트 삭제
 */
export const deleteTeamIdNotesNoteId = (
  teamId: string,
  noteId: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/${teamId}/notes/${noteId}`, method: "DELETE" },
    options,
  );
};
